export const SPECIALTIES = [
  "General Physician",
  "Cardiologist",
  "Dermatologist",
  "Dentist",
  "Gynecologist",
  "Pediatrician",
  "Orthopedic Surgeon",
  "ENT Specialist",
  "Ophthalmologist",
  "Psychiatrist",
  "Neurologist",
  "Urologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Endocrinologist",
  "Nephrologist",
  "Oncologist",
  "Rheumatologist",
  "Dietitian/Nutritionist",
  "Physiotherapist",
];

export const CITIES = [
  "Lahore",
  "Karachi",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Peshawar",
  "Quetta",
  "Hyderabad",
  "Sargodha",
  "Bahawalpur",
  "Sukkur",
  "Narowal",
];